apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankAuthentication
  labels:
    app: BankAuthentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankAuthentication
  template:
    metadata:
      labels:
        app: BankAuthentication
    spec:
      containers:
        - name: BankAuthentication
          image: username/BankAuthentication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5