apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankAccountHistory
  labels:
    app: BankAccountHistory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankAccountHistory
  template:
    metadata:
      labels:
        app: BankAccountHistory
    spec:
      containers:
        - name: BankAccountHistory
          image: username/BankAccountHistory:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5