apiVersion: apps/v1
kind: Deployment
metadata:
  name: LoanManager
  labels:
    app: LoanManager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LoanManager
  template:
    metadata:
      labels:
        app: LoanManager
    spec:
      containers:
        - name: LoanManager
          image: username/LoanManager:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5