---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankRequest
  labels:
    app: BankRequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankRequest
  template:
    metadata:
      labels:
        app: BankRequest
    spec:
      containers:
        - name: BankRequest
          image: username/BankRequest:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankAuthentication
  labels:
    app: BankAuthentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankAuthentication
  template:
    metadata:
      labels:
        app: BankAuthentication
    spec:
      containers:
        - name: BankAuthentication
          image: username/BankAuthentication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankAccount
  labels:
    app: BankAccount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankAccount
  template:
    metadata:
      labels:
        app: BankAccount
    spec:
      containers:
        - name: BankAccount
          image: username/BankAccount:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankAccountHistory
  labels:
    app: BankAccountHistory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankAccountHistory
  template:
    metadata:
      labels:
        app: BankAccountHistory
    spec:
      containers:
        - name: BankAccountHistory
          image: username/BankAccountHistory:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: MyPage
  labels:
    app: MyPage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MyPage
  template:
    metadata:
      labels:
        app: MyPage
    spec:
      containers:
        - name: MyPage
          image: username/MyPage:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: LoanRequest
  labels:
    app: LoanRequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LoanRequest
  template:
    metadata:
      labels:
        app: LoanRequest
    spec:
      containers:
        - name: LoanRequest
          image: username/LoanRequest:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: LoanAuthentication
  labels:
    app: LoanAuthentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LoanAuthentication
  template:
    metadata:
      labels:
        app: LoanAuthentication
    spec:
      containers:
        - name: LoanAuthentication
          image: username/LoanAuthentication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: LoanManager
  labels:
    app: LoanManager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LoanManager
  template:
    metadata:
      labels:
        app: LoanManager
    spec:
      containers:
        - name: LoanManager
          image: username/LoanManager:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: LoanStatus
  labels:
    app: LoanStatus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LoanStatus
  template:
    metadata:
      labels:
        app: LoanStatus
    spec:
      containers:
        - name: LoanStatus
          image: username/LoanStatus:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: LoanMessenger
  labels:
    app: LoanMessenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LoanMessenger
  template:
    metadata:
      labels:
        app: LoanMessenger
    spec:
      containers:
        - name: LoanMessenger
          image: username/LoanMessenger:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: BankRequest
  labels:
    app: BankRequest
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BankRequest


---


apiVersion: v1
kind: Service
metadata:
  name: BankAuthentication
  labels:
    app: BankAuthentication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BankAuthentication


---


apiVersion: v1
kind: Service
metadata:
  name: BankAccount
  labels:
    app: BankAccount
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BankAccount


---


apiVersion: v1
kind: Service
metadata:
  name: BankAccountHistory
  labels:
    app: BankAccountHistory
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: BankAccountHistory


---


apiVersion: v1
kind: Service
metadata:
  name: MyPage
  labels:
    app: MyPage
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: MyPage


---


apiVersion: v1
kind: Service
metadata:
  name: LoanRequest
  labels:
    app: LoanRequest
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: LoanRequest


---


apiVersion: v1
kind: Service
metadata:
  name: LoanAuthentication
  labels:
    app: LoanAuthentication
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: LoanAuthentication


---


apiVersion: v1
kind: Service
metadata:
  name: LoanManager
  labels:
    app: LoanManager
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: LoanManager


---


apiVersion: v1
kind: Service
metadata:
  name: LoanStatus
  labels:
    app: LoanStatus
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: LoanStatus


---


apiVersion: v1
kind: Service
metadata:
  name: LoanMessenger
  labels:
    app: LoanMessenger
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: LoanMessenger

