apiVersion: apps/v1
kind: Deployment
metadata:
  name: BankRequest
  labels:
    app: BankRequest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: BankRequest
  template:
    metadata:
      labels:
        app: BankRequest
    spec:
      containers:
        - name: BankRequest
          image: username/BankRequest:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5