apiVersion: apps/v1
kind: Deployment
metadata:
  name: LoanAuthentication
  labels:
    app: LoanAuthentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LoanAuthentication
  template:
    metadata:
      labels:
        app: LoanAuthentication
    spec:
      containers:
        - name: LoanAuthentication
          image: username/LoanAuthentication:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5