apiVersion: apps/v1
kind: Deployment
metadata:
  name: LoanMessenger
  labels:
    app: LoanMessenger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: LoanMessenger
  template:
    metadata:
      labels:
        app: LoanMessenger
    spec:
      containers:
        - name: LoanMessenger
          image: username/LoanMessenger:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5